Update to rom 5
rom-rb/rom-csv pull request #19
Opened 2021-02-13 16:03 UTC by pmackay

This is a fork of [this PR](https://github.com/rom-rb/rom-csv/pull/18) that was upgrading to ROM 4. The only extra change here is to set the version of ROM to 5.

2021-02-13 16:04 UTC, pmackay commented
@solnic I hope this is useful, it builds on the previous PR!

2021-02-15 06:02 UTC, solnic requested changes

2021-02-15 06:02 UTC, solnic commented on Gemfile
> +  end
This is not needed, rom master is no longer compatible with rom 5.x

2021-03-30 15:50 UTC, solnic approved these changes

2021-03-30 15:50 UTC, merged

2021-03-30 15:51 UTC, solnic commented
Thanks! I'll install devtools here so we can bring the codebase inline with the rest of the libs and we'll have to fix 3.0.0 compatibility and THEN I can release it 😅